name = "MeuNovoPacote"
uuid = "4f9ae77a-80f2-4771-a1b2-2d20cd25d1af"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.0-DEV"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
TestItemRunner = "0.2.2"
TestItems = "0.1.1"
StaticArrays = "1.6"
julia = "1"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "TestItemRunner"]
